name: Docker Image CI

on:
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  build:
    runs-on: python:alpine
    steps:
      - name: Check out code into module directory
        uses: actions/checkout@v1
      - name: Build + Publish Docker image
        uses: elgohr/Publish-Docker-Github-Action@2.11
        with:
          name: GRBurst/etesync
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          tag_names: true 
