name: Docker Image CI

on:
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into module directory
        uses: actions/checkout@v1
      - name: Docker Hub README & description sync
        uses: meeDamian/sync-readme@v1.0.6
        with:
          user: ${{ secrets.DOCKER_USERNAME }}
          pass: ${{ secrets.DOCKER_PASSWORD }}
          slug: grburst/etesync
          readme: true
          description: true
      - name: Build + Publish Docker image
        uses: elgohr/Publish-Docker-Github-Action@2.11
        with:
          name: grburst/etesync
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          tag_names: true 
