name: Update Docker Hub README everytime it changes on master

on:
  push:
    branches:
      - master
    paths:
      - README.md

jobs:
  sync:
    name: Update README to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into module directory
        uses: actions/checkout@v1

      - name: Sync README.md and Description to Docker Hub
        uses: meeDamian/sync-readme@v1.0.6
        with:
          user: ${{ secrets.DOCKER_USERNAME }}
          pass: ${{ secrets.DOCKER_PASSWORD }}
          slug: grburst/etesync
          description: true
